export const DEFAULT_AGENTS = [
  {
    code: "SP-001",
    description: "Organizes, implements, polishes.",
    focus: "Implementation",
    mediaLabel: "Gloopy hard-hat character",
    mediaMp4: "/onboarding/avatars/gloopies-20.mp4",
    mediaPng: "/onboarding/avatars/gloopies-20.png",
    name: "Kit",
    role: "Builder",
    skills: ["Organize", "Implement", "Polish"],
  },
  {
    code: "SP-002",
    description: "Investigates and flags issues.",
    focus: "Review",
    mediaLabel: "Low-poly dog character",
    mediaMp4: "/onboarding/avatars/pollies-24.mp4",
    mediaPng: "/onboarding/avatars/pollies-24.png",
    name: "Scout",
    role: "Reviewer",
    skills: ["Investigate", "Question", "Flag"],
  },
  {
    code: "SP-003",
    description: "Researches, builds, validates.",
    focus: "End-to-end",
    mediaLabel: "Fuzzy owl character",
    mediaMp4: "/onboarding/avatars/fuzzies-5.mp4",
    mediaPng: "/onboarding/avatars/fuzzies-5.png",
    name: "Solo",
    role: "All-in-one",
    skills: ["Research", "Plan", "Validate"],
  },
];
