// biome-ignore-all lint: generated by TanStack Router

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/root";
import { Route as reposRouteImport } from "./routes/repos";
import { Route as indexRouteImport } from "./routes/index";

const reposRoute = reposRouteImport.update({
  id: "/repos",
  path: "/repos",
  getParentRoute: () => rootRouteImport,
} as any);
const indexRoute = indexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof indexRoute;
  "/repos": typeof reposRoute;
}
export interface FileRoutesByTo {
  "/": typeof indexRoute;
  "/repos": typeof reposRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof indexRoute;
  "/repos": typeof reposRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/repos";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/repos";
  id: "__root__" | "/" | "/repos";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  indexRoute: typeof indexRoute;
  reposRoute: typeof reposRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/repos": {
      id: "/repos";
      path: "/repos";
      fullPath: "/repos";
      preLoaderRoute: typeof reposRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof indexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  indexRoute: indexRoute,
  reposRoute: reposRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
