import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import { tanstackRouter } from "@tanstack/router-plugin/vite";

// @ts-expect-error process is a nodejs global
const host = process.env.TAURI_DEV_HOST;

// https://vite.dev/config/
export default defineConfig(async () => ({
  plugins: [
    tanstackRouter({
      target: "react",
      routesDirectory: "./src/app/routes",
      generatedRouteTree: "./src/app/routeTree.gen.ts",
      virtualRouteConfig: "./src/app/routes.ts",
      quoteStyle: "double",
      semicolons: true,
      routeTreeFileHeader: [
        "// biome-ignore-all lint: generated by TanStack Router",
      ],
    }),
    react(),
  ],
  resolve: {
    // Use array form so we control match order: the longer
    // "@/features/huddle" prefix must be evaluated before the bare "@"
    // alias, otherwise Vite resolves @-paths via the broader rule first.
    // When VITE_SPROUT_HUDDLE=0 (desktop-light build), point the huddle
    // module at a no-op shim that exposes the same exports as
    // src/features/huddle/index.ts (HuddleProvider, useHuddle, HuddleBar,
    // HuddleIndicator, ParticipantList, setupAudioWorklet). Pairs with
    // the `huddle` Cargo feature in desktop/src-tauri/Cargo.toml.
    alias: [
      // @ts-expect-error process is a nodejs global
      ...(process.env.VITE_SPROUT_HUDDLE === "0"
        ? [
            {
              find: /^@\/features\/huddle$/,
              replacement: "/src/features/huddle/index.light.ts",
            },
          ]
        : []),
      { find: "@", replacement: "/src" },
    ],
  },

  // Vite options tailored for Tauri development and only applied in `tauri dev` or `tauri build`
  //
  // 1. prevent Vite from obscuring rust errors
  clearScreen: false,
  // 2. tauri expects a fixed port, fail if that port is not available
  server: {
    port: parseInt(process.env.VITE_PORT || "1420", 10),
    strictPort: true,
    host: host || false,
    hmr: host
      ? {
          protocol: "ws",
          host,
          port: parseInt(process.env.VITE_HMR_PORT || "1421", 10),
        }
      : undefined,
    watch: {
      // 3. tell Vite to ignore watching `src-tauri`
      ignored: ["**/src-tauri/**"],
    },
  },
}));
